base:
  project: diabetes-prediction
  random_state: 42
  target_col: Outcome

data_source:
  s3_source: source_data/diabetes.csv

load_data:
  raw_dataset: data/raw/diabetes.csv

split_data:
  train_path: data/processed/train_diabetes.csv
  test_path: data/processed/test_diabetes.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.9
      l1_ratio: 0.4

model_dir: models

reports:
  params: reports/params.json
  scores: reports/scores.json

webapp_model_dir: prediction_service/model/model.joblib

